# Generated by Django 4.0.6 on 2022-08-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_created=True)),
                ('fio', models.TextField()),
                ('age', models.IntegerField()),
                ('kind_of_sport', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
